import { products, about, contact, type Product } from './content';

export const escapeHTML = (value: string) => value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);
const e = escapeHTML;
export const productHref = (product: Product) => `/products/${product.id}`;
export const enquiryHref = (product?: Product) => `/contact${product ? `?product=${encodeURIComponent(product.id)}&type=demo` : ''}`;
const productArtwork = (product: Product) => ['credanta', 'vulcan'].includes(product.id) ? '/assets/products/network-infrastructure.jpg' : product.image;
const brandLockup = '<img class="brand-emblem" src="/assets/logo-transparent.png" alt="" width="48" height="48"><b class="brand-name">vyntiq<span>®</span></b>';

export function productRows(items = products) {
  return items.map((product, index) => `<a class="product-row" href="${productHref(product)}"><span class="product-index">0${index + 1}</span><span class="product-thumbnail"><img src="${productArtwork(product)}" alt="" loading="lazy"></span><span class="product-name">${e(product.name)}</span><span class="product-type">${e(product.badge)}</span><span class="product-description">${e(product.tagline)}</span><span class="product-arrow" aria-hidden="true">↗</span></a>`).join('');
}

export const header = (home = false) => `<header class="site-header"><a class="wordmark" href="${home ? '#top' : '/'}" aria-label="Vyntiq home">${brandLockup}</a><nav aria-label="Main navigation"><a href="${home ? '#products' : '/products'}">Products</a><a href="/about">About Vyntiq</a><a href="${home ? '#founders' : '/about#leadership'}">Founders</a><a href="/partners">Partners</a></nav><a class="header-action" href="/contact?type=demo">Request a demo <span>↗</span></a><button class="menu-toggle" aria-label="Open menu">Menu</button></header>`;
export const footer = () => `<footer class="site-footer"><div class="footer-brand"><a class="wordmark" href="/" aria-label="Vyntiq home">${brandLockup}</a><p>${e(about.company.motto)}</p><small>© 2026 ${e(about.company.legalName)}. All rights reserved.</small></div><nav aria-label="Footer navigation"><a href="/about">About Vyntiq</a><a href="/products">Products</a><a href="/partners">Partners</a><a href="/contact?type=demo">Request a demo</a></nav><div class="footer-emails">${Object.values(contact).map(email => `<a href="mailto:${email}">${email}</a>`).join('')}</div></footer>`;

export function founders(id = 'founders') {
  return `<section class="founders content-section" id="${id}"><div class="section-heading"><div><p class="kicker">Founders & leadership</p><h2>Leadership close<br>to the <em>work.</em></h2></div><p>Experience that stays close to product decisions.</p></div>${about.leadership.map((leader, index) => `<article class="founder founder-${index}"><figure class="founder-portrait"><img src="${leader.image}" alt="Portrait of ${e(leader.name)}" loading="lazy" width="902" height="1024"></figure><div class="founder-copy"><p class="founder-role">${e(leader.role)}</p><h3>${e(leader.name)}</h3><p class="founder-subtitle">${e(leader.subtitle)}</p><p class="founder-tagline">${e(leader.tagline)}</p><p class="founder-bio">${e(leader.bio)}</p></div></article>`).join('')}</section>`;
}

export const partnerSection = () => `<section class="partner-section content-section"><div class="section-heading"><div><p class="kicker">Partners</p><h2>Build meaningful<br><em>technology partnerships.</em></h2></div><p>We work with technology providers, implementation teams and organizations that can help bring dependable products into real operating environments.</p></div><div class="partner-bottom"><ul class="detail-list"><li>Technology and platform integrations</li><li>Implementation and solution partnerships</li><li>Joint product and market opportunities</li></ul><a class="button button-primary" href="/partners#enquiry">Start a partnership conversation <span>↗</span></a></div></section>`;

function detailSection(title: string, content: string, id = '') {
  return `<section class="detail-section content-section" ${id ? `id="${id}"` : ''}><h2>${title}</h2><div class="detail-copy">${content}</div></section>`;
}
function detailList(title: string, items: string[]) {
  return items.length ? detailSection(title, `<ul class="detail-list">${items.map(item => `<li>${e(item)}</li>`).join('')}</ul>`) : '';
}
function innerHero(title: string, kicker: string, copy: string) {
  return `<section class="inner-hero"><p class="kicker">${e(kicker)}</p><h1>${title}</h1><p class="inner-lede">${e(copy)}</p></section>`;
}

export function productPage(product: Product) {
  const pending = product.description === 'Product overview pending approved copy.';
  const proposed = product.copyStatus === 'proposed';
  const hero = `<section class="product-hero"><div class="product-hero-art" aria-hidden="true"><img src="${productArtwork(product)}" alt="" fetchpriority="high"></div><div class="product-hero-copy"><a class="back-link" href="/products">← All products</a><p class="kicker">${e(product.badge)}${proposed ? ' · Product concept' : ''}</p><h1>${e(product.name)}</h1><p class="product-tagline">${e(product.tagline)}</p><p class="product-overview">${e(product.description)}</p><a class="button button-primary" href="${enquiryHref(product)}">${pending || proposed ? 'Discuss this product' : 'Request a demo'} <span>↗</span></a></div><span class="art-caption">${proposed ? 'Concept illustration' : 'Product illustration'}</span></section>`;
  return `${hero}${pending ? detailSection('Product information', '<p>Approved product details will be added once supplied.</p>') : detailSection('The problem', `<p>${e(product.problemSolved)}</p>`) + detailList(proposed ? 'Proposed capabilities' : 'Key product features', product.features) + detailList('Product differentiators', product.differentiators) + detailList('Who it is for', product.targetCustomers) + detailList('Use cases', product.useCases) + detailList('Benefits', product.benefits)}${detailSection('Deployment', `<p>${e(product.deploymentModel)}</p>`)}${detailSection('Product status', `<p>${e(product.status)}</p>`)}<section class="products"><div class="section-heading"><div><h2>More from<br><em>Vyntiq.</em></h2></div><a class="text-link" href="/products">View all products <span>↗</span></a></div><div class="product-list">${productRows(products.filter(item => item.id !== product.id))}</div></section>`;
}

export function aboutPage() {
  const image = (src: string, alt: string, caption: string) => `<figure class="about-image"><img src="${src}" alt="${alt}" loading="lazy"><figcaption>${caption}</figcaption></figure>`;
  return `<div class="about-page"><section class="about-hero"><div class="about-hero-image" aria-hidden="true"><img src="/assets/about/city-blue-hour.png" alt="" fetchpriority="high"></div><div class="about-hero-copy"><p class="kicker">${e(about.company.motto)}</p><h1>Intelligent by design.<br><em>Practical by purpose.</em></h1><p>${e(about.company.overview)}</p><a class="text-link" href="#what-is-vyntiq">Discover Vyntiq <span>↓</span></a></div><span class="about-hero-note">Our journey begins in India. Our ambition is global.</span></section>
  <section class="about-intro content-section" id="what-is-vyntiq"><div class="about-intro-copy"><h2>Technology with<br><em>a reason to exist.</em></h2><p>${e(about.company.detail)}</p></div>${image('/assets/about/engineering-workspace.png', 'Hands collaborating on a circuit-board prototype at an engineering worktable', 'AI · Data · Software engineering · Deep technology')}</section>
  <section class="about-purpose content-section"><h2>${e(about.whyEstablished.title)}</h2><p>${e(about.whyEstablished.content)}</p><span>${e(about.whyEstablished.subtitle)}</span></section>
  <section class="about-principles content-section">${about.principles.map(principle => `<article><h2>${e(principle.title)}</h2><p>${e(principle.description)}</p></article>`).join('')}</section>
  <section class="about-direction content-section"><div class="about-direction-copy">${['mission', 'vision'].map(key => { const item = about.visionMission[key as 'mission' | 'vision']; return `<article id="${key}"><h2>${e(item.title)}</h2><p class="direction-statement">${e(item.statement)}</p><p>${e(item.detail)}</p></article>`; }).join('')}</div>${image('/assets/products/mukeradb-concept.png', 'Modern data infrastructure with blue and amber indicator lights', 'Dependable foundations. Lasting value.')}</section>
  ${detailSection('Meaningful problems.<br>Lasting value.', about.problemOpportunity.points.map(point => `<article class="capability"><h3>${e(point.title)}</h3><p>${e(point.desc)}</p></article>`).join(''))}
  <section class="about-specializations content-section"><div class="section-heading"><h2>Our <em>specializations.</em></h2><p>Intelligence, dependable foundations and purposeful engineering.</p></div><div class="specialization-scenes">${about.specializations.map((item, i) => `<article>${image(['/assets/products/crucible-concept.png', '/assets/products/network-infrastructure.jpg', '/assets/about/engineering-workspace.png'][i], ['Illustrative workspace connecting information and evidence', 'Server infrastructure illuminated by status lights', 'Hardware engineering and collaboration'][i], '')}<h3>${e(item.title)}</h3><p>${e(item.desc)}</p></article>`).join('')}</div></section>
  ${founders('leadership')}<section class="detail-section content-section where-we-work" id="where-we-work"><div class="industry-visual"><h2>Where we work</h2><figure class="industry-image"><img src="/assets/about/where-we-work-city.webp" alt="Modern glass office towers and a tree-lined public plaza illuminated at blue hour" loading="lazy" decoding="async" width="1024" height="1280"></figure></div><div class="detail-copy">${about.industryCapabilities.map(industry => `<article class="capability"><span>${e(industry.badge)}</span><h3>${e(industry.sector)}</h3><p>${e(industry.desc)}</p></article>`).join('')}</div></section>${partnerSection()}</div>`;
}

export function enquiryForm(partnership = false) {
  const selected = new URLSearchParams(location.search).get('product');
  const demo = new URLSearchParams(location.search).get('type') === 'demo';
  const options = partnership ? ['Technology integration', 'Implementation partnership', 'Joint product opportunity', 'Market and distribution partnership'] : ['General Business Enquiry', 'Request a Demo & Technical Pilot', 'Partnership Enquiry', 'Product and Implementation Enquiry'];
  return `<section class="enquiry-section content-section" id="enquiry"><div><h2>${partnership ? 'Start a partnership<br><em>conversation.</em>' : 'Start with<br><em>your context.</em>'}</h2><p>${partnership ? 'Tell us where our products, engineering capabilities or delivery experience could work together.' : 'Tell us about your organization, the product you are exploring and the requirements that matter.'}</p><div class="contact-channels">${Object.entries(contact).map(([label,email]) => `<a href="mailto:${email}"><span>${label === 'general' ? 'General enquiries' : label === 'sales' ? 'Sales & demos' : 'Contact Vyntiq'}</span>${email}</a>`).join('')}</div></div><form class="enquiry-form" data-partnership="${partnership}"><label>Your name<input required name="name" autocomplete="name"></label><label>Organization<input required name="organization" autocomplete="organization"></label><label>Business email<input required type="email" name="email" autocomplete="email"></label><label>Phone (optional)<input type="tel" name="phone" autocomplete="tel"></label><label class="full-field">${partnership ? 'Partnership area' : 'Enquiry type'}<select name="enquiryType">${options.map(option => `<option${!partnership && demo && option.startsWith('Request') ? ' selected' : ''}>${e(option)}</option>`).join('')}</select></label>${partnership ? '' : `<label class="full-field">Product of interest<select name="selectedProduct"><option value="">Select a product (optional)</option>${products.map(product => `<option value="${e(product.name)}"${product.id === selected ? ' selected' : ''}>${e(product.name)}</option>`).join('')}</select></label>`}<label class="full-field">${partnership ? 'How would you like to work together?' : 'Your message'}<textarea required name="message" rows="5"></textarea></label><p class="form-note full-field" role="status" aria-live="polite">Send your enquiry directly to the Vyntiq team.</p><a class="enquiry-email-fallback text-link full-field" hidden>Email this enquiry <span>↗</span></a><button class="button button-primary full-field" type="submit">Send enquiry <span>↗</span></button></form></section>`;
}

export function renderRoute(route: string) {
  const product = products.find(item => productHref(item) === route || (item.id === 'cop-ai' && route === '/products/copai') || (item.id === 'credanta' && route === '/products/credanta-certificate-lifecycle-management'));
  if (product) return { title: `${product.name} | Vyntiq`, copy: product.description, html: productPage(product) };
  if (route === '/about') return { title: 'About Vyntiq & Founders', copy: about.company.overview, html: aboutPage() };
  if (route === '/products') return { title: 'Products | Vyntiq', copy: 'Intelligent, high-quality products and solutions for real-world problems.', html: `${innerHero('Products built<br>to <em>make a difference.</em>', 'The Vyntiq portfolio', 'Intelligent, high-quality products and solutions for real-world problems.')}<section class="products route-products"><div class="product-list">${productRows()}</div></section>` };
  if (route === '/partners') return { title: 'Partner with Vyntiq', copy: 'Build meaningful technology partnerships with Vyntiq.', html: `${innerHero('Build meaningful<br><em>technology partnerships.</em>', 'Partners', 'We work with technology providers, implementation teams and organizations that can help bring dependable products into real operating environments.')}${partnerSection()}${enquiryForm(true)}` };
  if (route === '/contact') return { title: 'Contact Vyntiq', copy: 'Business enquiries, product demonstrations and partnerships.', html: `${innerHero('Let’s build<br><em>what matters.</em>', 'Contact Vyntiq', 'Business enquiries, product demonstrations and partnerships.')}${enquiryForm()}` };
  return { title: 'Page not found | Vyntiq', copy: 'The page you are looking for has moved.', html: `${innerHero('Page not found.', '404', 'The page you are looking for has moved.')}<section class="content-section"><a class="button button-primary" href="/">Back to Vyntiq</a></section>` };
}
